{
 "title": "API Performance 3.11",
 "time": { "from": "2020-07-22T02:22:50.000Z", "to": "2020-07-22T12:15:47.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(apiserver_request_count, instance)"
   },
   {
    "name": "resource",
    "label": "resource",
    "query": "label_values(apiserver_request_count, resource)"
   },
   { "name": "code", "label": "code", "query": "label_values(code)" },
   { "name": "verb", "label": "verb", "query": "label_values(verb)" },
   { "name": "period", "label": "interval", "query": "1m,5m" }
  ]
 },
 "panels": [
  {
   "title": "request duration - 99th quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket{instance=~\"$instance\",resource=~\"$resource\",subresource!=\"log\",verb!~\"WATCH|WATCHLIST|PROXY\"}[$period])) by(verb,le))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "request rate - by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{instance=~\"$instance\",resource=~\"$resource\",code=~\"$code\",verb=~\"$verb\"}[$period])) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "request duration - 99th quantile - by resource",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket{instance=~\"$instance\",resource=~\"$resource\",subresource!=\"log\",verb!~\"WATCH|WATCHLIST|PROXY\"}[$period])) by(resource,le))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "request rate - by resource",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{instance=~\"$instance\",resource=~\"$resource\",code=~\"$code\",verb=~\"$verb\"}[$period])) by(resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "request duration - read vs write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket{instance=~\"$instance\",resource=~\"$resource\",verb=~\"LIST|GET\"}[$period])) by(le))",
     "legendFormat": "read"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket{instance=~\"$instance\",resource=~\"$resource\",verb=~\"POST|PUT|PATCH|UPDATE|DELETE\"}[$period])) by(le))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "request rate - read vs write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{instance=~\"$instance\",resource=~\"$resource\",verb=~\"LIST|GET\"}[$period]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(apiserver_request_count{instance=~\"$instance\",resource=~\"$resource\",verb=~\"POST|PUT|PATCH|UPDATE|DELETE\"}[$period]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "request status rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\",code=~\"$code\"}[$period])) by(code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "long running requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_gauge{instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "response size - 99th quantile",
   "type": "graph",
   "description": "Response size distribution in bytes for each group, version, verb, resource, subresource, scope and component.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_response_sizes_bucket{instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\"}[$period])) by(instance,le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "request in flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests{instance=~\"$instance\"}) by (instance,requestKind)",
     "legendFormat": "{{requestKind}}-{{instance}}"
    }
   ]
  },
  {
   "title": "requests dropped rate",
   "type": "graph",
   "description": "Number of requests dropped with 'Try again later' response",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_dropped_requests{instance=~\"$instance\"}[$period])) by (requestKind)"
    }
   ]
  }
 ]
}