{
 "title": "API Health Endpoint",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "/healthz rate by code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"kube-apiserver\",verb=\"GET\",group=\"\",subresource=\"/healthz\"}[1m])) by(code)",
     "legendFormat": "/healthz : {{code}}"
    }
   ]
  },
  {
   "title": "/healthz latency 99th quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\",resource=\"\",subresource=\"/healthz\",verb=\"GET\"}[1m])) by(le))"
    }
   ]
  },
  {
   "title": "/readyz rate by code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"kube-apiserver\",verb=\"GET\",group=\"\",subresource=\"/readyz\"}[1m])) by(code)",
     "legendFormat": "/readyz : {{code}}"
    }
   ]
  },
  {
   "title": "/readyz latency 99th quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\",resource=\"\",subresource=\"/readyz\",verb=\"GET\"}[1m])) by(le))"
    }
   ]
  }
 ]
}