{
 "title": "Cluster Performance",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "apiserver",
    "label": "apiserver",
    "query": "label_values(apiserver_request_duration_seconds_bucket, apiserver)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(apiserver_request_total, instance)"
   },
   {
    "name": "resource",
    "label": "resource",
    "query": "label_values(apiserver_request_duration_seconds_bucket, resource)"
   },
   { "name": "code", "label": "code", "query": "label_values(code)" },
   { "name": "verb", "label": "verb", "query": "label_values(verb)" },
   { "name": "flowSchema", "label": "flow-schema", "query": "label_values(flowSchema)" },
   { "name": "priorityLevel", "label": "priority-level", "query": "label_values(priorityLevel)" },
   { "name": "period", "label": "interval", "query": "1m,5m" }
  ]
 },
 "panels": [
  {
   "title": "kubelet qps by code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (rate(rest_client_requests_total{service=\"kubelet\",job=\"kubelet\",code=~\"$code\"}[$period]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "kubelet qps by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(rest_client_requests_total{service=\"kubelet\",job=\"kubelet\",code=~\"$code\"}[$period]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "kube-controller-manager qps by code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (rate(rest_client_requests_total{service=\"kube-controller-manager\",job=\"kube-controller-manager\",code=~\"$code\"}[$period]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "kube-controller-manager qps by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(rest_client_requests_total{service=\"kube-controller-manager\",job=\"kube-controller-manager\",code=~\"$code\"}[$period]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "scheduler qps by code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (rate(rest_client_requests_total{service=\"scheduler\",job=\"scheduler\",code=~\"$code\"}[$period]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "scheduler qps by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(rest_client_requests_total{service=\"scheduler\",job=\"scheduler\",code=~\"$code\"}[$period]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}