{
 "title": "graceful termination",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "apiserver",
    "label": "apiserver",
    "query": "label_values(apiserver_request_duration_seconds_bucket, apiserver)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(apiserver_request_total, instance)"
   },
   {
    "name": "resource",
    "label": "resource",
    "query": "label_values(apiserver_request_duration_seconds_bucket, resource)"
   },
   { "name": "code", "label": "code", "query": "label_values(code)" },
   { "name": "verb", "label": "verb", "query": "label_values(verb)" },
   { "name": "flowSchema", "label": "flow-schema", "query": "label_values(flowSchema)" },
   { "name": "priorityLevel", "label": "priority-level", "query": "label_values(priorityLevel)" },
   {
    "name": "clientInstance",
    "label": "client instance",
    "query": "label_values(graceful_test_request_counter, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",code=~\"$code\"}[1m])) by(instance)"
    }
   ]
  },
  {
   "title": "request status by code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",code=~\"$code\"}[1m])) by(instance, code)"
    }
   ]
  },
  {
   "title": "rollout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(graceful_test_kubeapiserver_termination) by(instance)"
    }
   ]
  },
  {
   "title": "dropped requests by code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_dropped_requests_total{apiserver=\"$apiserver\",instance=~\"$instance\"}[5m])) by (requestKind)"
    }
   ]
  },
  {
   "title": "error seen by client",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(graceful_test_request_counter{code=\"<error>\",instance=~\"$clientInstance\"}[1m])) by(instance)"
    }
   ]
  },
  {
   "title": "latency",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",subresource!=\"log\",verb!~\"WATCH|WATCHLIST|PROXY|CONNECT\"}[1m])) by(resource,verb,le))"
    }
   ]
  },
  {
   "title": "client throughput ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(graceful_test_request_counter[1m])) by(instance,code)"
    }
   ]
  },
  {
   "title": "request in flight by kind",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests{apiserver=\"$apiserver\",instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "request termination rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_terminations_total{apiserver=\"$apiserver\",instance=~\"$instance\"}[1m])) by(component)"
    }
   ]
  },
  {
   "title": "long running (watches)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_gauge{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\"}) by(resource)"
    }
   ]
  }
 ]
}