{
 "title": "Dittybopper - Kube Cluster",
 "description": "Performance dashboard for Red Hat OpenShift",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "block_device",
    "label": "Block Device",
    "query": "label_values(node_disk_written_bytes_total,device)"
   },
   {
    "name": "net_device",
    "label": "Network Device",
    "query": "label_values(node_network_receive_bytes_total,device)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "etcd cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (rate(container_cpu_usage_seconds_total{container_name=\"etcd-metrics\"}[1m]))",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by (container_name) (rate(container_cpu_usage_seconds_total{container_name=\"etcd-member\"}[1m]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Pod Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{ node=\"master-0\"}) \n",
     "legendFormat": "master-0"
    },
    {
     "expr": "sum(kube_pod_info{node=\"master-1\"})\n",
     "legendFormat": "master-1"
    },
    {
     "expr": "sum(kube_pod_info{node=\"master-2\"})\n",
     "legendFormat": "master-2"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\"})",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})",
     "legendFormat": "Failed"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Failed Rest Client Request from KubeCTL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum by(instance, job) (rate(rest_client_requests_total{code!~\"2..\"}[5m]))/ sum by(instance, job) (rate(rest_client_requests_total[5m]))",
     "legendFormat": "{{instance}} - {{job}}"
    }
   ]
  }
 ]
}