{
 "title": "Dittybopper - Rook-Ceph",
 "description": "Performance dashboard for Red Hat OpenShift",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "block_device",
    "label": "Block Device",
    "query": "label_values(node_disk_written_bytes_total,device)"
   },
   {
    "name": "net_device",
    "label": "Network Device",
    "query": "label_values(node_network_receive_bytes_total,device)"
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Memory Usage : Master-0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{pod_name=~\"rook-ceph-osd.*\",instance=\"master0:10250\",container_name=\"osd\"}",
     "legendFormat": "{{pod_name}} - RSS"
    }
   ]
  },
  {
   "title": "OSD Memory Usage : Master-1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{pod_name=~\"rook-ceph-osd.*\",instance=\"master1:10250\",container_name=\"osd\"}",
     "legendFormat": "{{pod_name}} - RSS"
    }
   ]
  },
  {
   "title": "OSD Memory Usage : Master-2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{pod_name=~\"rook-ceph-osd.*\",instance=\"master2:10250\",container_name=\"osd\"}",
     "legendFormat": "{{pod_name}} - RSS"
    }
   ]
  },
  {
   "title": "Ceph-OSD :: Containers CPU usage (1m avg) ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{instance=\"master0:10250\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",container_name=~\"osd\"}[1m])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "Ceph-OSD :: Containers CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{instance=\"master1:10250\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",container_name=~\"osd\"}[1m])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "Ceph-OSD :: Containers CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{instance=\"master2:10250\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",container_name=~\"osd\"}[1m])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "Number of PVCs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info)\n",
     "legendFormat": "PVC Count"
    }
   ]
  },
  {
   "title": "Per-OSD Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate (ceph_osd_op_r_out_bytes{ceph_daemon=~\"osd.*\"}[1m] ) ",
     "legendFormat": "{{ceph_daemon}} - read"
    },
    {
     "expr": "irate (ceph_osd_op_w_in_bytes{ceph_daemon=~\"osd.*\"}[1m] ) ",
     "legendFormat": "{{ceph_daemon}} - write"
    },
    {
     "expr": "irate (ceph_osd_op_rw_in_bytes{ceph_daemon=~\"osd.*\"}[1m] )",
     "legendFormat": "{{ceph_daemon}} - read-modify-write in"
    },
    {
     "expr": "irate (ceph_osd_op_rw_out_bytes{ceph_daemon=~\"osd.*\"}[1m] )",
     "legendFormat": "{{ceph_daemon}} - read-modify-write out"
    }
   ]
  },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "ceph_osd_apply_latency_ms" }
   ]
  },
  {
   "title": "Avg OSD  Op  Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum[5m]) / rate(ceph_osd_op_r_latency_count[5m]) >= 0)",
     "legendFormat": "read"
    },
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum[5m]) / rate(ceph_osd_op_w_latency_count[5m]) >= 0)",
     "legendFormat": "write"
    }
   ]
  }
 ]
}