{
 "title": "Dittybopper Performance Dashboard",
 "description": "Performance dashboard for Red Hat OpenShift",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "block_device",
    "label": "Block Device",
    "query": "label_values(node_disk_written_bytes_total,device)"
   },
   {
    "name": "net_device",
    "label": "Network Device",
    "query": "label_values(node_network_receive_bytes_total,device)"
   }
  ]
 },
 "panels": [
  { "title": "Master Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load : Master-0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"master0:9100\"}",
     "legendFormat": "Load - 1m"
    },
    {
     "expr": "node_load5{instance=\"master0:9100\"}",
     "legendFormat": "Load - 5m"
    },
    {
     "expr": "node_load15{instance=\"master0:9100\"}",
     "legendFormat": "Load - 15m"
    }
   ]
  },
  {
   "title": "Load : Master-1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"master1:9100\"}",
     "legendFormat": "Load - 1m"
    },
    {
     "expr": "node_load5{instance=\"master1:9100\"}",
     "legendFormat": "Load - 5m"
    },
    {
     "expr": "node_load15{instance=\"master1:9100\"}",
     "legendFormat": "Load - 15m"
    }
   ]
  },
  {
   "title": "Load : Master-2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"master2:9100\"}",
     "legendFormat": "Load - 1m"
    },
    {
     "expr": "node_load5{instance=\"master2:9100\"}",
     "legendFormat": "Load - 5m"
    },
    {
     "expr": "node_load15{instance=\"master2:9100\"}",
     "legendFormat": "Load - 15m"
    }
   ]
  },
  {
   "title": "CPU Basic : Master-0",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"master0:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"master0:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"master0:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"master0:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"master0:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"master0:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU Basic : Master-1",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"master1:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"master1:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"master1:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"master1:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"master1:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"master1:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU Basic : Master-2",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"master2:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"master2:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"master2:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"master2:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"master2:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"master2:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic : Master-0",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"master0:9100\",job=~\".*\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"master0:9100\",job=~\".*\"} - node_memory_MemFree_bytes{instance=~\"master0:9100\",job=~\".*\"} - (node_memory_Cached_bytes{instance=~\"master0:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master0:9100\",job=~\".*\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"master0:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master0:9100\",job=~\".*\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"master0:9100\",job=~\".*\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"master0:9100\",job=~\".*\"} - node_memory_SwapFree_bytes{instance=~\"master0:9100\",job=~\".*\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Memory Basic : Master-1",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"master1:9100\",job=~\".*\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"master1:9100\",job=~\".*\"} - node_memory_MemFree_bytes{instance=~\"master1:9100\",job=~\".*\"} - (node_memory_Cached_bytes{instance=~\"master1:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master1:9100\",job=~\".*\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"master1:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master1:9100\",job=~\".*\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"master1:9100\",job=~\".*\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"master1:9100\",job=~\".*\"} - node_memory_SwapFree_bytes{instance=~\"master1:9100\",job=~\".*\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Memory Basic : Master-2",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"master2:9100\",job=~\".*\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"master2:9100\",job=~\".*\"} - node_memory_MemFree_bytes{instance=~\"master2:9100\",job=~\".*\"} - (node_memory_Cached_bytes{instance=~\"master2:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master2:9100\",job=~\".*\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"master2:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master2:9100\",job=~\".*\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"master2:9100\",job=~\".*\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"master2:9100\",job=~\".*\"} - node_memory_SwapFree_bytes{instance=~\"master2:9100\",job=~\".*\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Throughput : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"$block_device\",instance=\"master0:9100\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"$block_device\",instance=\"master0:9100\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk Throughput : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"$block_device\",instance=\"master1:9100\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"$block_device\",instance=\"master1:9100\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk Throughput : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"$block_device\",instance=\"master2:9100\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"$block_device\",instance=\"master2:9100\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk IOPS : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"$block_device\",instance=\"master0:9100\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"$block_device\",instance=\"master0:9100\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk IOPS : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"$block_device\",instance=\"master1:9100\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"$block_device\",instance=\"master1:9100\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk IOPS : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"$block_device\",instance=\"master2:9100\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"$block_device\",instance=\"master2:9100\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Network Utilization : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"master0:9100\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - RX"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"master0:9100\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - TX"
    }
   ]
  },
  {
   "title": "Network Utilization : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"master1:9100\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - RX"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"master1:9100\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - TX"
    }
   ]
  },
  {
   "title": "Network Utilization : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"master2:9100\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - RX"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"master2:9100\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - TX"
    }
   ]
  },
  {
   "title": "Process RSS : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\".*\",endpoint=~\".*\",instance=~\"master0.*\"}",
     "legendFormat": "{{ service }} - {{ job }}"
    }
   ]
  },
  {
   "title": "Process RSS : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\".*\",endpoint=~\".*\",instance=~\"master1.*\"}",
     "legendFormat": "{{ service }} - {{ job }}"
    }
   ]
  },
  {
   "title": "Process RSS : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\".*\",endpoint=~\".*\",instance=~\"master2.*\"}",
     "legendFormat": "{{ service }} - {{ job }}"
    }
   ]
  },
  {
   "title": "CPU Usage : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{instance=\"master0:10250\"}[5m])",
     "legendFormat": "{{ pod_name }} - {{ service }}"
    }
   ]
  },
  {
   "title": "CPU Usage : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{instance=\"master1:10250\"}[5m])",
     "legendFormat": "{{ pod_name }} - {{ service }}"
    }
   ]
  },
  {
   "title": "CPU  Usage : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{instance=\"master2:10250\"}[5m])",
     "legendFormat": "{{ pod_name }} - {{ service }}"
    }
   ]
  },
  { "title": "Rook-Ceph Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "OSD Memory Usage : Master-0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{pod_name=~\"rook-ceph-osd.*\",instance=\"master0:10250\",container_name=\"osd\"}",
     "legendFormat": "{{pod_name}} - RSS"
    }
   ]
  },
  {
   "title": "OSD Memory Usage : Master-1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{pod_name=~\"rook-ceph-osd.*\",instance=\"master1:10250\",container_name=\"osd\"}",
     "legendFormat": "{{pod_name}} - RSS"
    }
   ]
  },
  {
   "title": "OSD Memory Usage : Master-2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{pod_name=~\"rook-ceph-osd.*\",instance=\"master2:10250\",container_name=\"osd\"}",
     "legendFormat": "{{pod_name}} - RSS"
    }
   ]
  },
  {
   "title": "Number of PVCs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info)\n",
     "legendFormat": "PVC Count"
    }
   ]
  },
  {
   "title": "Per-OSD Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate (ceph_osd_op_r_out_bytes{ceph_daemon=~\"osd.*\"}[1m] ) ",
     "legendFormat": "{{ceph_daemon}} - read"
    },
    {
     "expr": "irate (ceph_osd_op_w_in_bytes{ceph_daemon=~\"osd.*\"}[1m] ) ",
     "legendFormat": "{{ceph_daemon}} - write"
    },
    {
     "expr": "irate (ceph_osd_op_rw_in_bytes{ceph_daemon=~\"osd.*\"}[1m] )",
     "legendFormat": "{{ceph_daemon}} - read-modify-write in"
    },
    {
     "expr": "irate (ceph_osd_op_rw_out_bytes{ceph_daemon=~\"osd.*\"}[1m] )",
     "legendFormat": "{{ceph_daemon}} - read-modify-write out"
    }
   ]
  },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    { "expr": "ceph_osd_apply_latency_ms" }
   ]
  },
  {
   "title": "Avg OSD  Op  Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum[5m]) / rate(ceph_osd_op_r_latency_count[5m]) >= 0)",
     "legendFormat": "read"
    },
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum[5m]) / rate(ceph_osd_op_w_latency_count[5m]) >= 0)",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "etcd cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (rate(container_cpu_usage_seconds_total{container_name=\"etcd-metrics\"}[1m]))",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by (container_name) (rate(container_cpu_usage_seconds_total{container_name=\"etcd-member\"}[1m]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Pod Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{host_ip=\"master0\"}) \n",
     "legendFormat": "master0"
    },
    {
     "expr": "sum(kube_pod_info{host_ip=\"master1\"})\n",
     "legendFormat": "master1"
    },
    {
     "expr": "sum(kube_pod_info{host_ip=\"master2\"})\n",
     "legendFormat": "master2"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\"})",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})",
     "legendFormat": "Failed"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Failed Rest Client Request from KubeCTL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum by(instance, job) (rate(rest_client_requests_total{code!~\"2..\"}[5m]))/ sum by(instance, job) (rate(rest_client_requests_total[5m]))",
     "legendFormat": "{{instance}} - {{job}}"
    }
   ]
  }
 ]
}