{
 "title": "Dittybopper - Master Nodes",
 "description": "Performance dashboard for Red Hat OpenShift",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "block_device",
    "label": "Block Device",
    "query": "label_values(node_disk_written_bytes_total,device)"
   },
   {
    "name": "net_device",
    "label": "Network Device",
    "query": "label_values(node_network_receive_bytes_total,device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load : Master-0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"master0:9100\"}",
     "legendFormat": "Load - 1m"
    },
    {
     "expr": "node_load5{instance=\"master0:9100\"}",
     "legendFormat": "Load - 5m"
    },
    {
     "expr": "node_load15{instance=\"master0:9100\"}",
     "legendFormat": "Load - 15m"
    }
   ]
  },
  {
   "title": "Load : Master-1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"master1:9100\"}",
     "legendFormat": "Load - 1m"
    },
    {
     "expr": "node_load5{instance=\"master1:9100\"}",
     "legendFormat": "Load - 5m"
    },
    {
     "expr": "node_load15{instance=\"master1:9100\"}",
     "legendFormat": "Load - 15m"
    }
   ]
  },
  {
   "title": "Load : Master-2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"master2:9100\"}",
     "legendFormat": "Load - 1m"
    },
    {
     "expr": "node_load5{instance=\"master2:9100\"}",
     "legendFormat": "Load - 5m"
    },
    {
     "expr": "node_load15{instance=\"master2:9100\"}",
     "legendFormat": "Load - 15m"
    }
   ]
  },
  {
   "title": "CPU Basic : Master-0",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"master0:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"master0:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"master0:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"master0:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"master0:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"master0:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU Basic : Master-1",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"master1:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"master1:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"master1:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"master1:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"master1:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"master1:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU Basic : Master-2",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"master2:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"master2:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"master2:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"master2:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"master2:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"master2:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "System Memory : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"master0:9100\",job=~\".*\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_Active_bytes{instance=~\"master0:9100\",job=~\".*\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"master0:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master0:9100\",job=~\".*\"}",
     "legendFormat": "Cached + Buffers"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"master0:9100\",job=~\".*\"} - (node_memory_Cached_bytes{instance=~\"master0:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master0:9100\",job=~\".*\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "System Memory : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"master1:9100\",job=~\".*\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_Active_bytes{instance=~\"master1:9100\",job=~\".*\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"master1:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master1:9100\",job=~\".*\"}",
     "legendFormat": "Cached + Buffers"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"master1:9100\",job=~\".*\"} - (node_memory_Cached_bytes{instance=~\"master1:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master1:9100\",job=~\".*\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "System Memory : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"master2:9100\",job=~\".*\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_Active_bytes{instance=~\"master2:9100\",job=~\".*\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"master2:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master2:9100\",job=~\".*\"}",
     "legendFormat": "Cached + Buffers"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"master2:9100\",job=~\".*\"} - (node_memory_Cached_bytes{instance=~\"master2:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"master2:9100\",job=~\".*\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Throughput : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"$block_device\",instance=\"master0:9100\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"$block_device\",instance=\"master0:9100\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk Throughput : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"$block_device\",instance=\"master1:9100\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"$block_device\",instance=\"master1:9100\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk Throughput : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"$block_device\",instance=\"master2:9100\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"$block_device\",instance=\"master2:9100\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk IOPS : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"$block_device\",instance=\"master0:9100\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"$block_device\",instance=\"master0:9100\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk IOPS : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"$block_device\",instance=\"master1:9100\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"$block_device\",instance=\"master1:9100\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk IOPS : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"$block_device\",instance=\"master2:9100\"}[1m])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"$block_device\",instance=\"master2:9100\"}[1m])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Network Utilization : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"master0:9100\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - RX"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"master0:9100\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - TX"
    }
   ]
  },
  {
   "title": "Network Utilization : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"master1:9100\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - RX"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"master1:9100\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - TX"
    }
   ]
  },
  {
   "title": "Network Utilization : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"master2:9100\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - RX"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"master2:9100\",device=~\"$net_device\"}[1m]) * 8",
     "legendFormat": "{{device}} - TX"
    }
   ]
  },
  {
   "title": "Process RSS : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\".*\",endpoint=~\".*\",instance=~\"master0.*\"}",
     "legendFormat": "{{ service }} - {{ job }}"
    }
   ]
  },
  {
   "title": "Process RSS : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\".*\",endpoint=~\".*\",instance=~\"master1.*\"}",
     "legendFormat": "{{ service }} - {{ job }}"
    }
   ]
  },
  {
   "title": "Process RSS : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\".*\",endpoint=~\".*\",instance=~\"master2.*\"}",
     "legendFormat": "{{ service }} - {{ job }}"
    }
   ]
  },
  {
   "title": "CPU Usage : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{instance=\"master0:10250\"}[5m])",
     "legendFormat": "{{ pod_name }} - {{ service }}"
    }
   ]
  },
  {
   "title": "CPU Usage : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{instance=\"master1:10250\"}[5m])",
     "legendFormat": "{{ pod_name }} - {{ service }}"
    }
   ]
  },
  {
   "title": "CPU  Usage : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{instance=\"master2:10250\"}[5m])",
     "legendFormat": "{{ pod_name }} - {{ service }}"
    }
   ]
  }
 ]
}